#lang sicp

; Exercise 1.14:
; ==============
; Draw the tree illustrating the process generated by the count-change procedure
; of Section 1.2.2 in making change for 11 cents.
; What are the orders of growth of the space and number of steps used by this
; process as the amount to be changed increases?

; (count-change 11)                                                             
; |                                                                             
; |                                                                             
; (cc 11 4)                                                                     
; |        \_                                                                   
; |          \                                                                  
; (cc 11 3)   (cc -39 4)                                                        
; |       \___    (0)                                                           
; |           \                                                                 
; (cc 11 2)   (cc -14 3)                                                        
; |       \_______(0)_________________________________________                  
; |                                                           \                 
; (cc 11 1)                                                   (cc 1 2)          
; |       \_______________________                            |     \__         
; |                               \                           |        \        
; (cc 11 0)                       (cc 6 1)                    (cc 1 1) (cc -9 2)
; |       \__                     |      \__                  |     \__  (0)    
; |          \                    |         \                 |        \        
; (cc 11 -1) (cc 10 0)            (cc 6 0) (cc 1 1)           (cc 1 0) (cc -4 1)
;    (0)   _/|                 __/|        |    \__           |     \__   (0)   
;         /  |                /   |        |       \          |        \        
; (cc 10 -1) (cc 9 0)  (cc 6 -1)  (cc 5 0) (cc 1 0) (cc -4 1) (cc 1 -1) (cc 0 0)
;    (0)   _/|           (0)   __/|        |    \____   (0)      (0)      (1)   
;         /  |                /   |        |         \                          
; (cc 9 -1)  (cc 8 0)  (cc 5 -1)  (cc 4 0) (cc 1 -1) (cc 0 0)                   
;    (0)   _/|           (0)   __/|           (0)      (1)                      
;         /  |                /   |                                             
; (cc 8 -1)  (cc 7 0)  (cc 4 -1)  (cc 3 0)                                      
;    (0)   _/|           (0)   __/|                                             
;         /  |                /   |                                             
; (cc 7 -1)  (cc 6 0)  (cc 3 -1)  (cc 2 0)                                      
;    (0)   _/|           (0)   __/|                                             
;         /  |                /   |                                             
; (cc 6 -1)  (cc 5 0)  (cc 2 -1)  (cc 1 0)                                      
;    (0)   _/|           (0)  __/                                               
;         /  |                /   |                                             
; (cc 5 -1)  (cc 4 0)  (cc 1 -1)  (cc 0 0)                                      
;    (0)   _/|           (0)       (1)                                          
;         /  |                                                                  
; (cc 4 -1)  (cc 3 0)                                                           
;    (0)   _/|                                                                  
;         /  |                                                                  
; (cc 3 -1)  (cc 2 0)                                                           
;    (0)   _/|                                                                  
;         /  |                                                                  
; (cc 2 -1)  (cc 1 0)                                                           
;    (0)   _/|                                                                  
;         /  |                                                                  
; (cc 1 -1)  (cc 0 0)                                                           
;    (0)       (1)                                                              
;
; Modified ASCII graph from http://community.schemewiki.org/?sicp-ex-1.14.

; Space complexity: Most space is needed for the combination containing juts n
; times the coin 1. Here the space used will be O(n). If we used coins of bigger
; value, we would require less coins in total to change the given amount.

; Determining the time complexity is a bit trickier. If we just used one coin,
; the complexity would be O(n), just like the maximum required space. If we add
; another coin, on each step we have to decide if we continue using just the
; first coin or use the second.
; If we used the second coin (of value 5), we could use it at most
; n/5 times. For each such branch we also have the choice to just switch to
; using the first coin. So the complexity would be approximately n * n/5.
; 5 is a constant and becomes insignificant for large values of n, so the time
; complexity is O(n^2).
; For each additional coin we can use, the complexity gets multiplied by n, so
; if we have 5 different coins to choose from, the computation complexity is
; O(n^5).